### ISSUE TITLE
How does the Bruteforce App differentiate between internal and external?

### ISSUE THREAD

**Issue by HassanMullah** [nextcloud/bruteforcesettings#199]
Hi, I have a question. I have an Apache reverse proxy running on a Raspberry PI. This Raspberry PI has both an internal IPv4 address and an external IPv4 address (via NAT from the router). If I now whitelist 192.168.1.0/23 (my subnet is 255.255.255.254.0, therefore 23), the Raspberry PI would be included. 

If someone accesses the Nextcloud via the full qualified domain name and tries to break in with Bruteforce, how does the Bruteforce App behave?

Do we here recognize that the break-in comes from outside?

**Comment by Sk1pp3r** [comment]
if my understanding is correct, if the device (let's call it device A) accesses the cloud via its internal IP, then `nextcloud` sees its internal IP, which probably falls in the range that you whitelisted, otherwise it's going to see the external IP address and might block it if it detects bruteforcing...

You can try to login from that device A via `nextcloud` LAN address with wrong password, and then via domain name with wrong password. After that go to `nextcloud` webpage, log in with admin credentials and go to Settings -> Logging and you should see something like the following:

![failed_login](https://user-images.githubusercontent.com/2412881/83506859-643b9280-a4d0-11ea-8ae2-407d9637ceb4.jpg)

**Comment by patschi** [comment]
This is correct: The checks are based on IP addresses/ranges. Which IP your Nextcloud sees, depends on your exact setup (e.g. reverse proxy and `X-Forwarded-For` headers, etc). As the question was addressed, I'm assuming this is solved and closing this issue. If not, feel free to re-open and report back.
