### ISSUE TITLE
Update for Nextcloud 21

### ISSUE THREAD

**Issue by protist** [nextcloud/bruteforcesettings#255]
I just upgraded to Nextcloud 21.0.0, and during the upgrade was told `Disabled incompatible app: bruteforcesettings`. In the GUI:

```
This app cannot be installed because the following dependencies are not fulfilled:

    Server version 20 or lower is required.
```

**Comment by BkSouX** [comment]
is #259 enough ?

**Comment by vwbusguy** [comment]
That's enough to allow it to be installed in the NextCloud apps section, assuming the dev signs it.  I enabled it in my Nextcloud 21 and it doesn't seem to be broken so far as I can tell but I haven't extensively tested it.

**Comment by patschi** [comment]
This is covered in #262 (with some additional changes) and currently PR #264 is pending for approval with some dependency-rework. Then I think we're good to go for a new release.

**Comment by rakekniven** [comment]
@rullzer @MorrisJobke Have you seen this issue?

**Comment by Siggi0904** [comment]
With nc 21.0.1 in stable channel the addon is very urgently needed.
Please update the addon.

**Comment by gautamkrishnar** [comment]
👁️

**Comment by udf2457** [comment]
👀 Urgently needed post 21.0.1 upgrade !

**Comment by MakselPr** [comment]
Tell me please. How to install a package manually ?

**Comment by rakekniven** [comment]
> Tell me please. How to install a package manually ?

https://lmgtfy.app/?q=nextcloud+app+manual+installation

**Comment by MakselPr** [comment]
> 
> 
> > Tell me please. How to install a package manually ?
> 
> https://lmgtfy.app/?q=nextcloud+app+manual+installation

Yj

> 
> 
> > Tell me please. How to install a package manually ?
> 
> https://lmgtfy.app/?q=nextcloud+app+manual+installation

that's not it.

sudo -u www-data php occ app: install bruteforcesettings
bruteforcesettings already installed
  sudo -u www-data php occ app: enable bruteforcesettings
App "Brute-force settings" cannot be installed because it is not compatible with this version of the server.

Does not help.
 An old application is being installed.
And I wanted to know how to apply the application from the git. What files can be replaced manually.

**Comment by patschi** [comment]
> And I wanted to know how to apply the application from the git. What files can be replaced manually.

You can't do that easily, because the sources need to be built using `npm`.

For people who can't or don't want to wait, I've packaged the current state of the source code of this app. 

There are few things to note:
1. The version of the app is based on today's state and is equal to 2.1.0. 
2. The package below has version 2.0.9 set and the purpose is that once the app update is published to the AppStore, that the updater notices the update.
3. The app name has a suffix `[CUSTOM]` to indicate this is a custom build.
4. The app is not signed.
5. Once the new update is published, I'm going to remove the download.
6. Usual disclaimer: On your own risk, etc.

Commands:
```
cd /var/www/nextcloud/apps/
mv bruteforcesettings/ /tmp/backup_bruteforcesettings/
wget https://patrik.kernstock.net/files/bruteforcesettings_209.tar.gz
tar zfx bruteforcesettings_209.tar.gz
rm bruteforcesettings_209.tar.gz
```

**Comment by slawa-dev** [comment]
> Tell me please. How to install a package manually ?

All you really need is to manually bump `max-version="21"` in `/apps/bruteforcesettings/appinfo/info.xml`

like in this pull request 
https://github.com/nextcloud/bruteforcesettings/pull/259/files

Then just wait for the app to get the update for other changes.

**Comment by shadowlmd** [comment]
App got automatically disabled after NC updated to 21.0.1.
![image](https://user-images.githubusercontent.com/969156/114301182-57160980-9acc-11eb-96d4-46e8f4e15818.png)

**Comment by rakekniven** [comment]
https://apps.nextcloud.com/apps/bruteforcesettings Update vor NC21 is out!

**Comment by Siggi0904** [comment]
@rakekniven then update the dependencies too. They the old information.
And check the "enable untested app" information and remove it.

With app version 2.1.0

![grafik](https://user-images.githubusercontent.com/4992106/114311114-c4866200-9aed-11eb-91dd-3e7a499aec2f.png)
