### ISSUE TITLE
Empty mask field leads to an inappropriate default IP range

### ISSUE THREAD

**Issue by hobbsecky** [nextcloud/bruteforcesettings#289]
When adding an IP address to the whitelist without entering a range currently 192.168.0.1 becomes 192.168.0.1/0

/0 implies that you are whitelisting EVERYTHING!

That should **NOT** be the default result of an entry with no range.

If a user inputs JUST the IP address: 192.168.0.1
The whitelist should append the range with /32 so the net result is you are adding ONLY a single IP address:
192.168.0.1/32

Thanks!

**Comment by nursoda** [comment]
I agree that it should not become /0, but I disagree that THIS particular address should become /32. For well-known address ranges such as [RFC1918](https://datatracker.ietf.org/doc/html/rfc1918) addresses, please resolve to their default, which is 192.168/16 in this case.

And…since bruteforcesettings is an official app and this bug may lead to security relevant misconfiguration, this should be resolved by the team if no one else creates a PR. This bug is open for eight months now…

**Comment by joshtrichards** [comment]
Good catch 👍

If we were to assume a single IP or a particular CIDR range, both assumptions could still be incorrect and still lead to a misconfiguration.

Since we have no way of knowing the user's true intentions - and this is a security related value field - 
I think preventing the mask field from being empty - and also not providing a default - best addresses this situation.

This could be enforced here:

https://github.com/nextcloud/bruteforcesettings/blob/a1112ca000791c519d8838523100b52020d680c1/src/App.vue#L45-L65
