### ISSUE TITLE
Add to Whitelist button does not function when clicked after adding one entry

### ISSUE THREAD

**Issue by coyoteconscious** [nextcloud/bruteforcesettings#559]
[Nextcloud Hub 6](https://nextcloud.com/) (27.1.6)
Ubuntu 23.10

I have a new install of Nextcloud, and went in to do the initial setup, including whitelisting some ips.

I entered one local ip, and it seemed to add fine. When I attempted to add _any_ other entries (including re-adding the first entry when I deleted it), the button highlights when clicked, but nothing happens.

So I was able to add one simple local ip, but nothing else, and when I deleted it, I could not  re-add the same entry or any other entries.

This one's new to me. It usually works without pain.

**Comment by joshtrichards** [comment]
What browser is this? I can't reproduce this (at least in Firefox ESR).

Also, for the record, the UI just got some mostly behind the scenes cleanup in #552 thanks to @DorraJaouad. That'll make an appearance in v27.1.7. That may help since it eliminated some legacy ways we were still doing things in this app.
